name: Moodle Plugin CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-18.04

    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_USER: 'postgres'
          POSTGRES_HOST_AUTH_METHOD: 'trust'
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 3
      mariadb:
        image: mariadb:10
        env:
          MYSQL_USER: 'root'
          MYSQL_ALLOW_EMPTY_PASSWORD: "true"
          MYSQL_CHARACTER_SET_SERVER: "utf8mb4"
          MYSQL_COLLATION_SERVER: "utf8mb4_unicode_ci"

        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval 10s --health-timeout 5s --health-retries 3

    strategy:
      fail-fast: false
      matrix: # I don't know why, but mariadb is much slower, so mostly use pgsql.
        include:
          - php: '8.0'
            moodle-branch: 'master'
            database: 'pgsql'

    steps:
      - name: Install required libraries
        run: |
          sudo apt-get install maxima maxima-share
          maxima --list-avail
          echo "diff(x^2,x);" | maxima
          echo "build_info();" | maxima
          ls -l /usr/share/maxima/5.41.0/share/draw
          cat /usr/share/maxima/5.41.0/share/draw/draw.lisp
          echo "load(\"stats\");" | maxima
          gcc --version
